name: Hermes feedback
description: Report feedback on the experience of using an early access release compatible with the Hermes JS engine. See also [#3940](https://github.com/realm/realm-js/issues/3940).
labels: [hermes]
body:
  - type: markdown
    attributes:
      value: |
        We [are working hard](https://github.com/realm/realm-js/pull/3792) on getting Hermes supported by Realm JavaScript,
        and we are releasing a series of pre-releases to test our progress.
# Description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe what you were expecting and what actually happened.
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace & log output
      description: Please paste any relevant log output or stacktrace if you're getting an exception/crash.
      render: shell
# Repro information
  - type: dropdown
    id: repro
    attributes:
      label: Can you reproduce a bug?
      options:
        - Yes, always
        - Yes, sometimes
        - Not yet
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Reproduction Steps
      description: |
        If you can reproduce a bug, please provide detailed steps for how WE can reproduce it.
        Ideally, please provide a self contained test case or link (e.g. github repo) to a sample app that demonstrates the bug.
        If that's not possible, please show code samples that highlight or reproduce the issue.
        If relevant, include your model definitions.
        Should you need to share code confidentially, you can send a link to: realm-help (the @) mongodb.com.
# Version
  - type: input
    id: version
    attributes:
      label: Version
      description: What version(s) of the SDK has the bug been observed in?
    validations:
      required: true
  - type: dropdown
    id: sync
    attributes:
      label: What SDK flavour are you using?
      options:
        - Local Database only
        - Atlas Device Sync
        - Atlas App Services (auth, functions, etc.)
  - type: dropdown
    id: encryption
    attributes:
      label: Are you using encryption?
      options:
        - Yes, using encryption
        - No, not using encryption
# Environment
  - type: input
    id: platform
    attributes:
      label: Platform OS and version(s)
      description: OS and version(s) are you seeing the issue on?
    validations:
      required: true
