platform :ios, '9.0'

target 'ReactTestApp' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ], :inhibit_warnings => true
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :inhibit_warnings => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :inhibit_warnings => true
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :inhibit_warnings => true
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :inhibit_warnings => true
  pod 'RNFS', :path => '../node_modules/react-native-fs', :inhibit_warnings => true

  target 'RealmReactTests' do
    inherit! :search_paths
  end
end
