/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reacttests_API */

#ifndef _Included_com_reacttests_RealmReactAndroid
#define _Included_com_reacttests_RealmReactAndroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reacttests_RealmReactAndroid
 * Method:    getDefaultRealmFileDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_reacttests_RealmReactAndroid_getDefaultRealmFileDirectory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
