/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reacttests_API */


#include "com_reacttests_API.h"
/*
 * Class:     com_reacttests_API
 * Method:    getDefaultRealmFileDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_reacttests_API_getDefaultRealmFileDirectory
  (JNIEnv *env, jclass) 
  {

	 return env->NewStringUTF("Hello from JNI ! ");
  }

