/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reacttests_API */

#ifndef _Included_com_reacttests_API
#define _Included_com_reacttests_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reacttests_API
 * Method:    getDefaultRealmFileDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_reacttests_API_getDefaultRealmFileDirectory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
