/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_react_RealmReactModule */

#ifndef _Included_io_realm_react_RealmReactModule
#define _Included_io_realm_react_RealmReactModule
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:      io_realm_react_RealmReactModule
* Method:     setDefaultRealmFileDirectory
*/
JNIEXPORT void JNICALL Java_io_realm_react_RealmReactModule_setDefaultRealmFileDirectory
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_realm_react_RealmReactModule
 * Method:    setupChromeDebugModeRealmJsContext
 */
JNIEXPORT jlong JNICALL Java_io_realm_react_RealmReactModule_setupChromeDebugModeRealmJsContext
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_react_RealmReactModule
 * Method:    processChromeDebugCommand
 */
JNIEXPORT jstring JNICALL Java_io_realm_react_RealmReactModule_processChromeDebugCommand
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     io_realm_react_RealmReactModule
 * Method:    tryRunTask
 */
JNIEXPORT jboolean JNICALL Java_io_realm_react_RealmReactModule_tryRunTask
(JNIEnv *, jclass);

/*
 * Class:     io_realm_react_RealmReactModule
 * Method:    isContextInjected
 */
JNIEXPORT jboolean JNICALL Java_io_realm_react_RealmReactModule_isContextInjected
    (JNIEnv *, jclass);

/*
 * Class:     io_realm_react_RealmReactModule
 * Method:    clearContextInjectedFlag
 */
JNIEXPORT void JNICALL Java_io_realm_react_RealmReactModule_clearContextInjectedFlag
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
