/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_react_RealmReactAndroid */

#ifndef _Included_io_realm_react_RealmReactAndroid
#define _Included_io_realm_react_RealmReactAndroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_react_RealmReactAndroid
 * Method:    injectRealmJsContext
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jlong JNICALL Java_io_realm_react_RealmReactAndroid_injectRealmJsContext
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_realm_react_RealmReactAndroid
 * Method:    setupChromeDebugModeRealmJsContext
 */
JNIEXPORT jlong JNICALL Java_io_realm_react_RealmReactAndroid_setupChromeDebugModeRealmJsContext
  (JNIEnv *, jclass);

/*
 * Class:     io_realm_react_RealmReactAndroid
 * Method:    processsetupChromeDebugCommand
 */
JNIEXPORT jstring JNICALL Java_io_realm_react_RealmReactAndroid_processChromeDebugCommand
  (JNIEnv *, jclass, jlong, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
