/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_react_RealmReactModule */

#ifndef _Included_io_realm_react_RealmReactModule
#define _Included_io_realm_react_RealmReactModule
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:      io_realm_react_RealmReactModule
* Method:     setDefaultRealmFileDirectory
*/
JNIEXPORT void JNICALL Java_io_realm_react_RealmReactModule_setDefaultRealmFileDirectory
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
