require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ReactTestApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # Since this is a project within RealmJS, we need to add the pod manually.
  # This is due to the fact that its not a dependecy in our package.json and
  # the automatic linking will not pick it up.
  pod 'RealmJS', :path => '../../../', :inhibit_warnings => true

  target 'ReactTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
        end
      end
    end
  end
end
