require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Remove all warnings to limit the build logs
inhibit_all_warnings!

target 'RealmReactNativeTests' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'RealmReactNativeTestsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # To disable Flipper, set the environment variable `DISABLE_FLIPPER` to 'true'
  if ENV['CI'] != 'true' && ENV['DISABLE_FLIPPER'] != 'true'
    use_flipper!()
  end

  post_install do |installer|
    react_native_post_install(installer)
    # TODO: The following is a workaround for a bug in CocoaPods when using Catalyst  
    # https://github.com/CocoaPods/CocoaPods/issues/8891
    # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
        end
      end
    end
  end
end
