require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Remove all warnings to limit the build logs
inhibit_all_warnings!

target 'RealmReactNativeTests' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Since we're installing Realm using install-local,
  # auto-linking won't find a key for it in our package.json's dependencies,
  # hence, we need to add this manually
  pod 'RealmJS', :path => '../../../..', :inhibit_warnings => false

  target 'RealmReactNativeTestsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end