# This workflow builds the @realm/react Typedoc and publishes it to https://docs.mongodb.com/realm-sdks/js/realm-react/latest/.
# It also uploads them to a versioned directory for archival purposes.

name: Realm React Docs Publish
on:
  push:
    tags:
      - realm-react-v[0-9]+\.[0-9]+\.[0-9]+
  workflow_dispatch:

env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  publish:
    name: Build & Publish Realm React Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm v8
        run: npm install -g npm@8
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - name: Install root package dependencies
        run: npm ci --ignore-scripts
      - name: Build docs
        run: cd packages/realm-react && npm run docs
      - name: Set up S3cmd and configure AWS credentials
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws
          region: "us-west-1"
          access_key: ${{ secrets.DOCS_S3_ACCESS_KEY }}
          secret_key: ${{ secrets.DOCS_S3_SECRET_KEY }}
      # Get the version number so we can specify the correct path for uploading the docs
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      # --no-mime-magic --guess-mime-type flags to work around CSS incorrect MIME type issue
      # (https://stackoverflow.com/questions/53708938/s3cmd-flagging-css-with-wrong-mime-type)
      - name: Upload versioned docs (for archival)
        run: s3cmd put --recursive --acl-public --no-mime-magic --guess-mime-type docs/ s3://${{ secrets.DOCS_S3_BUCKET_NAME }}/docs/realm-sdks/js/realm-react/${{ steps.package-version.outputs.current-version}}/
      - name: Upload latest docs (to live site)
        run: s3cmd put --recursive --acl-public --no-mime-magic --guess-mime-type docs/ s3://${{ secrets.DOCS_S3_BUCKET_NAME }}/docs/realm-sdks/js/realm-react/latest/
