name: Analytics (Pull Request)
on: pull_request
env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  analytics:
    name: Analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install npm v7
        run: npm install -g npm@7
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - name: Install root package dependencies
        run: npm ci --ignore-scripts
      - name: Install subpackages dependencies
        run: npm run lerna:bootstrap
      - name: Run postinstall script
        run: |
          cd integration-tests/tests
          tmpfile=$(mktemp)
          node ../../scripts/submit-analytics.js --test > $tmpfile
          cat $tmpfile | grep ^payload | cut -f2- -d' ' | jq '.webHook.properties' | jq 'keys' | jq 'join(",")' | grep -c 'Anonymized Application ID,Anonymized Machine Identifier,Binding,Framework,Framework Version,Host OS Type,Host OS Version,JS Analytics Version,JavaScript Engine,Language,Node.js version,Version,distinct_id,token'