name: Testing Babel Plugin (Pull Request)

env:
  REALM_DISABLE_ANALYTICS: 1

on:
  pull_request:
    paths:
      - "*"
      - "lib/**"
      - "src/**"
      - "types/**"
      - "react-native/**"
      - "vendor/**"
      # Integration tests
      - "integration-tests/**"
      - "packages/babel-plugin/**"
      - ".github/workflows/pr-babel-plugin.yml"
      # No need to run when updating documentation
      - "!**.md"
jobs:
  job:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install npm v7
        run: npm install -g npm@8

      # Caches
      - uses: actions/cache@v3
        name: cached node_modules
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ github.job }}-${{ hashFiles('package-lock.json') }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-linux-x64
          max-size: '2.0G'

      - name: Prepend ccache executables to the PATH
        run: echo PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

      - name: Install realm node dependencies
        run: npm ci --ignore-scripts

      - name: Bootstrap @realm/babel-plugin
        run: npx lerna bootstrap --scope @realm/babel-plugin --include-dependencies

      - name: Build realm react
        working-directory: packages/babel-plugin
        run: npm run build

      - name: Run tests
        working-directory: packages/babel-plugin
        run: npm test
