name: Publish Babel Plugin

on:
  push:
    tags:
      - babel-plugin-v*
env:
  REALM_DISABLE_ANALYTICS: 1

jobs:
  test-build-and-publish:
    name: Test, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm v7
        run: npm install -g npm@8
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - run: npm ci --ignore-scripts
      # Bootstrap lerna sub-packages
      - run: npx lerna bootstrap --scope @realm/babel-plugin --include-dependencies
      # Test the package
      - run: npm test
        working-directory: packages/babel-plugin
      # Publish the package
      - run: npm publish
        working-directory: packages/babel-plugin
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
