name: Publish Realm React Native templates

on:
  workflow_dispatch:

jobs:
  publish-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish templates
        run: templates/scripts/publish_templates.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
